version: 1.0

system: "cls_n_b_1000"

ddim:
  num_train: 1000
  num_inference: 50
  beta_start: 0.0001
  beta_end: 0.02
  v_predictionn: False

diffwrap:
  fusion: concat
  pre_hidden: 256

  use_timbre_feature: False
  timbre_feature_dim: None

  use_timbre_model: False

  use_event_ppg: False

  unet:  
    sample_size: [64, 400]
    in_channels: None
    out_channels: 1
    layers_per_block: 2
    block_out_channels: [128, 256, 512, 512]
    down_block_types: 
      ["DownBlock2D",
      "DownBlock2D",
      "AttnDownBlock2D",
      "AttnDownBlock2D",
      ]
    up_block_types:
      ["AttnUpBlock2D",
      "AttnUpBlock2D",
      "UpBlock2D",
      "UpBlock2D"
      ]
    num_class_embeds: 41
    attention_head_dim: 32